"""Add is_admin column to User model

Revision ID: 878f7c3823a1
Revises: 
Create Date: 2024-10-09 20:39:34.676185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878f7c3823a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Username', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('Email', sa.String(length=125), nullable=False))
        batch_op.add_column(sa.Column('Password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.create_unique_constraint(None, ['Username'])
        batch_op.drop_column('password')
        batch_op.drop_column('id')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('Password')
        batch_op.drop_column('Email')
        batch_op.drop_column('Username')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###
